apiVersion: v1
kind: Service
metadata:
  name: hypothyroid-service
  # namespace: hypothyroid-namespace
  labels:
    app: hypothyroid
spec:
  type: LoadBalancer
  selector:
    app: hypothyroid
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hypothyroid-deployment
  # namespace: hypothyroid-namespace
  labels:
    app: hypothyroid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hypothyroid
  template:
    metadata:
      labels:
        app: hypothyroid
    spec:
      containers:
      - name: hypothyroid
        image: jun222work/hypothyroid:V1
        ports:
        - containerPort: 80